name: draught
description: A web application to aid in my fantasy football draft.
dependencies:
  core_elements: '>=0.2.0 <0.3.0'
  paper_elements: '>=0.1.1 <0.1.2'
  path: any
  polymer: '>=0.13.0 <0.14.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
